### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-auth#3]
Here is the new design: [LOGIN_ID_SMARTCITIZEN.pdf](https://github.com/fablabbcn/smartcitizen-auth/files/2191843/LOGIN_ID_SMARTCITIZEN.pdf)

Currently we have no framework and everything is very minimal.

Should we add a CSS framework like Bootstrap to speed up development, and be more compatible on different browsers? 
But with the overhead of a CSS framework?

I will say yes :nerd_face:

**Comment by marcelirodriguez** [comment]
[START_SCK.pdf](https://github.com/fablabbcn/smartcitizen-auth/files/2495619/START_SCK.pdf)
